# Generated by Django 2.1.7 on 2019-07-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbscopy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
