# Generated by Django 2.1.7 on 2019-07-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbscopy', '0003_auto_20190731_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='author',
            new_name='user',
        ),
    ]
