# Generated by Django 2.1.7 on 2019-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbscopy', '0004_auto_20190731_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='', max_length=500),
        ),
    ]
